"""fix unfinished reports columns

Revision ID: 236b42a57544
Revises: 5b1946e8dfc8
Create Date: 2026-03-16 11:13:54.584599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '236b42a57544'
down_revision: Union[str, Sequence[str], None] = '5b1946e8dfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unfinished_reports', sa.Column('report_json', sa.JSON(), nullable=True))
    op.add_column('unfinished_reports', sa.Column('chat_history', sa.JSON(), nullable=True))
    op.add_column('unfinished_reports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('unfinished_reports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('unfinished_reports', 'report_data')
    op.drop_column('unfinished_reports', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unfinished_reports', sa.Column('last_updated', sa.DATETIME(), nullable=True))
    op.add_column('unfinished_reports', sa.Column('report_data', sqlite.JSON(), nullable=True))
    op.drop_column('unfinished_reports', 'updated_at')
    op.drop_column('unfinished_reports', 'created_at')
    op.drop_column('unfinished_reports', 'chat_history')
    op.drop_column('unfinished_reports', 'report_json')
    # ### end Alembic commands ###
