"""add witness_nominations and notification_type

Revision ID: 44800dc994c8
Revises: e524288daf72
Create Date: 2026-04-14 10:45:08.910271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44800dc994c8'
down_revision: Union[str, Sequence[str], None] = 'e524288daf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
