"""add historical incidents table properly

Revision ID: 8a70aeab36c3
Revises: e46d6b6e80f3
Create Date: 2026-03-25 13:51:15.363477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a70aeab36c3'
down_revision: Union[str, Sequence[str], None] = 'e46d6b6e80f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('plant', sa.String(), nullable=True),
    sa.Column('person_involved', sa.String(), nullable=True),
    sa.Column('person_type', sa.String(), nullable=True),
    sa.Column('actions_taken', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('sif_case', sa.String(), nullable=True),
    sa.Column('accident_type', sa.String(), nullable=True),
    sa.Column('accident_agent', sa.String(), nullable=True),
    sa.Column('injury_type', sa.String(), nullable=True),
    sa.Column('injury_agent', sa.String(), nullable=True),
    sa.Column('damage_amount', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('incident_activity', sa.String(), nullable=True),
    sa.Column('incident_agent', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_incidents_accident_type'), 'historical_incidents', ['accident_type'], unique=False)
    op.create_index(op.f('ix_historical_incidents_id'), 'historical_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_historical_incidents_incident_type'), 'historical_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_historical_incidents_injury_type'), 'historical_incidents', ['injury_type'], unique=False)
    op.create_index(op.f('ix_historical_incidents_location'), 'historical_incidents', ['location'], unique=False)
    op.create_index(op.f('ix_historical_incidents_source_id'), 'historical_incidents', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_incidents_source_id'), table_name='historical_incidents')
    op.drop_index(op.f('ix_historical_incidents_location'), table_name='historical_incidents')
    op.drop_index(op.f('ix_historical_incidents_injury_type'), table_name='historical_incidents')
    op.drop_index(op.f('ix_historical_incidents_incident_type'), table_name='historical_incidents')
    op.drop_index(op.f('ix_historical_incidents_id'), table_name='historical_incidents')
    op.drop_index(op.f('ix_historical_incidents_accident_type'), table_name='historical_incidents')
    op.drop_table('historical_incidents')
    # ### end Alembic commands ###
