"""add witness_nominations

Revision ID: e524288daf72
Revises: 11997af0964f
Create Date: 2026-04-14 10:06:49.254355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e524288daf72'
down_revision: Union[str, Sequence[str], None] = '11997af0964f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_reports', sa.Column('witness_nominations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_reports', 'witness_nominations')
    # ### end Alembic commands ###
